import type { Metadata } from "next";
import { Toaster } from "react-hot-toast";
import "./globals.css";

export const metadata: Metadata = {
  title: "DarulKubra -student registration",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html love-deals="879BC0364EB9EBEE3DBE71B15E175613">
      <body>
        <Toaster position="top-center" />
        {children}
      </body>
    </html>
  );
}
